### PR TITLE
Job to delete and relogin Google accounts on ATV

### PR DESCRIPTION
**Pull request by DrMurx**
This helps to mitigate the occasional issues with Google accounts.

The login job assumes the presence a file named `/sdcard/google-account` with the Google email address in line 1 and the Google password in line 2.

### CODE REVIEW

**Comment by krzee** [comment]
tested?

**Comment by ColdShadow80** [comment]
If it works, it would be great to see it on a new flash in a MAD rom.
That and a WiFi autoconfig would be nice a upgrade for a new release.

**Comment by krzee** [comment]
that would be pretty sweet and i already need to re-do autoconfig, i will look in to it. in the meantime it'll be super helpful to know this pr has been tested and works. because i agree that if this pr works it should probably work during autoconfig too

**Comment by ColdShadow80** [comment]
I will run a test on a couple of ATVs after dinner too. Will post feedback later

**Comment by DrMurx** [comment]
Tested, of course. I'm using it since weeks now.

**Comment by krzee** [comment]
really nice work

**Comment by DrMurx** [comment]
Be aware that the login relies on a responsive UI. There are some `sleep` in the sequence, but there's no check whether the "Account Login Activity" is actually on the screen and with the right field in focus, which means it might just fail in some cases or do something very unexpected if another Activity pops up in between.

Somebody with some decent Android coding skills might be able to develop a CLI tool which could do the same directly.

**Comment by krzee** [comment]
or we can loop increasing the sleep time if needed

**Comment by krzee** [comment]
or just error on the side of safety and sleep moar
if that made this work in autoconfig it would be worth doing. the juice is worth the squeeze

**Comment by DrMurx** [comment]
You can probably loop in a script but not really in a MAD command (it has to be a single command without any `;` in it).

What we could do is to turn `16mad` into a library of various functions. It needs a safeguarded default entrypoint which is called when `16mad` is executed in boot context but not called when `16mad` is source'd in another script.

Doing so will have all the complex functions in a single file (=easy update), and this file still serves as `16mad` initscript, but its functions could also be triggered through a MAD command for complex operations or to re-run parts of the autoconfig.

**Comment by krzee** [comment]
you're thinking of update_mad.sh :)

**Comment by DrMurx** [comment]
That's also an option. :)

**Comment by JabLuszko** [comment]
> You can probably loop in a script but not really in a MAD command (it has to be a single command without any `;` in it).

They fixed it, you can `;` now. 

Also to make sure UI is working we could (never tested, someone need to test) use `uiautomator dump` and look for keyword in that xml.

**Comment by ColdShadow80** [comment]
I confirm Account removal job worked.
Sadly, "Google Account: login " did not. Instead of login in using email, it tried several times to login "using phone or laptop".<
Using a A95X F1 in the test.

**Comment by DrMurx** [comment]
@ColdShadow80 I've tested it on my x96mini. The Login Activity might just look different in other environment and provide other UI elements.

**Comment by krzee** [comment]
x96 mini and a95xf1both use s905w rom; what version of the installer did each of you use?
id expect the differences to take place on different installers, which could be accounted for in the scripts once we know where the differences are

**Comment by DrMurx** [comment]
I believe this change could mitigate the issue, unless there are more conditions which make the first screen of the Login Activity look different.

**Comment by ColdShadow80** [comment]
Works. 
Followed job with scrcpy and login was a success

**Comment by krzee** [comment]
maybe put a seatbelt on it and not run either job if /sdcard/google-account does not exist?

**Comment by ColdShadow80** [comment]
Removal could benefict from some safety net, but I saw no need on the Add account job. Without a file it will have no login details and would expire.
But a "No sdcard/google-account file found" message as a result on the job would make sence

**Comment by krzee** [comment]
i guess thats true, i was thinking of it as a 2 step process, which you dont really want to begin if you wont succeed all the way (what if you didnt backup the account info and it results in a sad sad day?)

**Comment by ColdShadow80** [comment]
Then, to be fair and for it to be a true failsafe, we should also check if file has content because some idiots manage to create empty files...
By some idiots I meant me... About 2 hours ago 🤣

By no means I think we should validate every thing. 

But in theory, we could store a backup of the login (email) used on the device when the Remove login job is used. A log stored on the SD card folder would take no storage space at all.

**Comment by krzee** [comment]
im talking to banana about getting google login info stored in devices section of madmin (google email is already there, but not password) and then giving us a way to get these via pogodroid endpoint.
then if the madmin settings allow that device to give its google info via pogodroid we could make this job get google data directly from madmin instead of requiring /sdcard/google-account and a readme and all that

**Comment by krzee** [comment]
in the meantime i have used this personally and it totally did the job. at first it wasnt working right but after a reboot it was perfect (thats not the jobs fault). im happy you invented this method :)

**Comment by krzee** [comment]
can you please make the delete google account job check for /sdcard/google-account before it removes the account? This way if somebody runs the wrong job it doesnt kick their ass if they arent prepared to run the job which fixes it

**Comment by DrMurx** [comment]
> can you please make the delete google account job check for /sdcard/google-account before it removes the account? This way if somebody runs the wrong job it doesnt kick their ass if they arent prepared to run the job which fixes it

@krzee Voila.

**Pull request merged**
