### PR TITLE
Create custom_get_google_accounts

### PR DESCRIPTION
**Pull request by JabLuszko**
List google accounts (I hope, checking contacts sync) logged into device. Need more testing for devices with few accounts, I have one account per device.

### CODE REVIEW

**Review by krzee — COMMENTED** [review]
wanna give this command a shot?
yours works, but it hurts me to see 3 commands where it should be 1 :D
If mine doesnt work im fine with using yours.

`awk -F'\"' '/com.android.contacts\"/{print $8}' /data/system/sync/accounts.xml`

**Comment by marcb1387** [comment]
both worked the same for me.

**Comment by JabLuszko** [comment]
My phones do not have awk, cut is there for purpose. I do not really want to make this ATV only.

**Comment by krzee** [comment]
fair enough

**Comment by DrMurx** [comment]
I might be pedantic or a little OCD, but: filename and indent... 🙄

**Comment by krzee** [comment]
if you PR i will accept :)

**Pull request merged**
