### PR TITLE
Command for enable/disable PD MockLocation on ATV

### PR DESCRIPTION
**Pull request by moltova**
Personal ATV command for enable or disable mock_location in PogoDroid with reboot.

### CODE REVIEW

**Comment by krzee** [comment]
This can not be added as an ATV job. the name and filename need to be changed if you want it included as a custom phone job, MAD-ATV ROM will disable this and install smali. we tested pogodroid mocking and it was a problem.

**Comment by krzee** [comment]
do not run this on your atv.

**Comment by moltova** [comment]
ok, i remove this command, but mock_location works fine on my atvs.

**Comment by krzee** [comment]
https://github.com/Map-A-Droid/MAD-ATV/blob/master/16mad#L141

the mad rom disagrees with you. we moved to PD mocking a couple months ago and it gave everybody error 11 or 12, i forget which. Now the above line disables PD mocking on ATVs runing mad rom.
so if you run a proper version of mad rom you DO NOT have PD mocking enabled.

**Pull request closed without merging**
