### PR TITLE
Improve "get google accounts"

### PR DESCRIPTION
**Pull request by DrMurx**
See #5 - I've aligned filenames and formatting.

I also took the liberty of refining the job. `grep` and `cut` are not the best tools for parsing XML. The previous implementation depends on the position of the `account` parameters in the XML tag in `accounts.xml`. With `awk` we properly parse the `acccount` parameter regardless of its position in the file.

### CODE REVIEW

**Comment by krzee** [comment]
See the conversation here about awk:
https://github.com/Map-A-Droid/MAD_Personal_Commands/pull/5

**Comment by DrMurx** [comment]
Valid point. I'll rethink this, put it on hold. :)

**Comment by krzee** [comment]
we could still rename and change indents tho

**Comment by DrMurx** [comment]
Naming needs more discussion. It's not strictly an ATV command and since we migrated to the new repo, it doesn't make sense anymore to prefix everything with `madatv_`.

**Pull request closed without merging**
